/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sf_unixsocket_UnixSocket_Native */

#ifndef _Included_sf_unixsocket_UnixSocket_Native
#define _Included_sf_unixsocket_UnixSocket_Native
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     sf_unixsocket_UnixSocket_Native
 * Method:    listen
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_sf_unixsocket_UnixSocket_00024Native_listen
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     sf_unixsocket_UnixSocket_Native
 * Method:    accept
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_sf_unixsocket_UnixSocket_00024Native_accept
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     sf_unixsocket_UnixSocket_Native
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_sf_unixsocket_UnixSocket_00024Native_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     sf_unixsocket_UnixSocket_Native
 * Method:    read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_sf_unixsocket_UnixSocket_00024Native_read
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     sf_unixsocket_UnixSocket_Native
 * Method:    write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_sf_unixsocket_UnixSocket_00024Native_write
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     sf_unixsocket_UnixSocket_Native
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sf_unixsocket_UnixSocket_00024Native_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     sf_unixsocket_UnixSocket_Native
 * Method:    closeInput
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sf_unixsocket_UnixSocket_00024Native_closeInput
  (JNIEnv *, jclass, jint);

/*
 * Class:     sf_unixsocket_UnixSocket_Native
 * Method:    closeOutput
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sf_unixsocket_UnixSocket_00024Native_closeOutput
  (JNIEnv *, jclass, jint);

///*
// * Class:     sf_unixsocket_UnixSocket_Native
// * Method:    unlink
// * Signature: (Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_sf_unixsocket_UnixSocket_00024Native_unlink
//  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
