/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sf_unixsocket_TimedInputStream */

#ifndef _Included_sf_unixsocket_TimedInputStream
#define _Included_sf_unixsocket_TimedInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef sf_unixsocket_TimedInputStream_MAX_SKIP_BUFFER_SIZE
#define sf_unixsocket_TimedInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#ifdef __cplusplus
}
#endif
#endif
