/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sf_unixsocket_UnixServerSocket */

#ifndef _Included_sf_unixsocket_UnixServerSocket
#define _Included_sf_unixsocket_UnixServerSocket
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
