/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sf_unixsocket_UnixClientSocket */

#ifndef _Included_sf_unixsocket_UnixClientSocket
#define _Included_sf_unixsocket_UnixClientSocket
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
